language: java

services:
  - postgresql

jdk:
- openjdk8

env:
- TERM=dumb



install:
  - gradle assemble

before_script:
  - psql -c 'create database eventlab;' -U postgres

addons:
  postgresql: "9.6"



script:
  - gradle check

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/